project:
  type: website

website:
  title: "QuartoWS2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://www.isg-institut.de/
        text: ISG Homepage
      - about.qmd
  page-footer: 
    left: "© 2023 Hans Verbeek"
    center: "Powered by [quarto](https://quarto.org)"
    right: 
      - icon: github
      - href: https://github.com/tiefenbeek

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto